deployment:
  name: helm-test-cartapi
  replicaCount: "1"
  ContainerPort: "8080"
image: 
  name: "vintilaterraform.azurecr.io/cartapi"
  tag: "v5"


secret:
  name: "acr-secret"


service:
  name: "cartapi-service"
  port: "80"
  targetPort: "8080"
  type: "NodePort"